baseURL = 'http://blog.polybit.io/'
languageCode = 'en-GB'
title = 'Fizz Co.'
theme = 'hugo-theme-monochrome'
defaultContentLanguage = "en"
paginate = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


[[navbar]]
identifier = "Fizz Co"
name = "Fizz Co"
url = "/posts/fizzco/"
weight = 6

[goldmark.renderer]
unsafe= true

[highlight]
anchorLineNos = false
codeFences = false
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noHl = false
noClasses = true
style = "monokai"
tabWidth = 4
